### ISSUE TITLE
Why the $full_name?

### ISSUE THREAD

**Issue by aquister** [cristifalcas/puppet-heka#40]
What is your reasoning for using $full_name? This breaks the entire module.

When referencing a decoder for instance, you need to use the full_name and not the name you have set as the puppet resource title.

**Comment by cristifalcas** [comment]
Can you explain in more details what is the problem? The changes shouldn't have had any impact on you at all.

And about the reasoning to use an internal variable instead of the name:
- all plugins are using heka::snippet directly now
- because of this, the template is rendered inside the plugin (not in heka::snippet) and it can access either the plugin name, or the variable
- because different plugins can have the same name, templates are using the variable full_name, which has concatenated the plugin name to the resource name
- all templates are supposedly updated to use @full_name instead of @name

**Comment by aquister** [comment]
Before the implementation of full_name:

`heka::decoder::multidecoder { 'UNIQUE_NAME': }`
`heka::inputs::udpinput { 'udpinputtitle':`
`decoder => 'UNIQUE_NAME'`
`}`

With the implementation of full_name:

`heka::decoder::multidecoder { 'UNIQUE_NAME': }`
`heka::inputs::udpinput { 'udpinputtitle':`
`decoder => 'multidecoder_UNIQUE_NAME'`
`}`

So it does very much affect the use of the module.

**Comment by cristifalcas** [comment]
You are correct. Sorry about the breakage. It should be fixed in the latest commit. I will do some tests and release a new version

**Comment by cristifalcas** [comment]
Fixed
